# Day 1 - Part 1)

The first order of business is to figure out how quickly the depth increases, just so you know what you're dealing with - you never know if the keys will get carried into deeper water by an ocean current or a fish or something.

To do this, count the number of times a depth measurement increases from the previous measurement. 

In [6]:
import numpy as np

### Example

In [16]:
test_data = np.array([199, 200, 208, 210, 200, 207, 240, 269, 260, 263])

In [31]:
test_data[:-1] # omit last element # can't compare depth measurement with last reading

array([199, 200, 208, 210, 200, 207, 240, 269, 260])

In [27]:
test_data[1:] # omit 1st element; this is the n+1 array, as in the next measurement

array([200, 208, 210, 200, 207, 240, 269, 260, 263])

In [29]:
test_data[:-1] < test_data[1:]

array([ True,  True,  True, False,  True,  True,  True, False,  True])

In [23]:
(test_data[:-1] < test_data[1:]).sum()

7

### Actual data

In [11]:
data = np.loadtxt('day1_input.txt', dtype='int')
data

array([ 171,  173,  174, ..., 3267, 3280, 3282])

In [24]:
(data[:-1] < data[1:]).sum()

1266

# Part 2)

Start by comparing the first and second three-measurement windows. The measurements in the first window are marked A (199, 200, 208); their sum is 199 + 200 + 208 = 607. The second window is marked B (200, 208, 210); its sum is 618. The sum of measurements in the second window is larger than the sum of the first, so this first comparison increased.

Basically, it's a sliding-door avg with 3 values

### Example

In [38]:
test_data

array([199, 200, 208, 210, 200, 207, 240, 269, 260, 263])

In [76]:
number_of_groups = 8 # is it just n-2?
group_sum = []
for n in range(0, number_of_groups):
    group_sum.append(test_data[n:n+3].sum())
    
    # for every group of 3 values - sum(), iterate 1 value and sum again()
    
    #easier to append values in a list; will convert to array after

group_sum_ar = np.asarray(group_sum)

In [77]:
(group_sum_ar[:-1] < group_sum_ar[1:]).sum()

5

### Actual data

In [79]:
len(data)

2000

In [80]:
number_of_groups = len(data)-2 # is it just n-2?
group_sum = []
for n in range(0, number_of_groups):
    group_sum.append(data[n:n+3].sum())
    #using a list instead of a np.array, as it's easier to append values
    # will convert to array after

group_sum_ar = np.asarray(group_sum)

In [82]:
group_sum_ar

array([ 518,  510,  498, ..., 9798, 9811, 9829])

In [81]:
(group_sum_ar[:-1] < group_sum_ar[1:]).sum()

1217